# Generated by Django 2.2.8 on 2021-01-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_orden_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obras.Obra'),
        ),
    ]
