# Generated by Django 2.2.8 on 2021-01-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_auto_20210116_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'verbose_name_plural': 'Detalles Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'Orden'},
        ),
        migrations.AlterField(
            model_name='orden',
            name='encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
