# Generated by Django 2.2 on 2021-01-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_auto_20210116_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='faltante',
            field=models.BooleanField(default=False),
        ),
    ]
