# Generated by Django 3.2 on 2022-05-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capataz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('apellido', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Capataces',
            },
        ),
    ]
