# Generated by Django 3.2 on 2022-05-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Obras',
            },
        ),
    ]
