# Generated by Django 2.2.8 on 2021-01-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obra',
            options={'verbose_name_plural': 'Obras'},
        ),
    ]
