# Generated by Django 2.2.8 on 2021-03-16 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositocantidad',
            name='cantidad_minima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='depositocantidad',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material'),
        ),
    ]
