# Generated by Django 2.2 on 2021-05-03 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
        ('contratistas', '0001_initial'),
        ('ordenes', '0006_detalleorden_faltante'),
        ('obras', '0002_auto_20210116_2241'),
        ('depositos', '0002_auto_20210315_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratistas.Contratista')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obras.Obra')),
            ],
            options={
                'verbose_name_plural': 'Deposito Orden',
            },
        ),
        migrations.CreateModel(
            name='DepositoDetalleOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faltante', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depositos.DepositoOrden')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.Unidad')),
            ],
            options={
                'verbose_name_plural': 'Deposito Detalles Ordenes',
            },
        ),
    ]
