# Generated by Django 3.2 on 2022-04-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_material_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
