# Generated by Django 3.2 on 2022-04-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materiales.unidad'),
        ),
    ]
